"""add chunk metadata

Revision ID: 0c04db5809d0
Revises: a5613a1ee964
Create Date: 2026-09-02 11:03:24.630185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c04db5809d0'
down_revision: Union[str, Sequence[str], None] = 'a5613a1ee964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('manual_chunks', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.alter_column('manual_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('manual_chunks', 'section_title')
    op.drop_column('manual_chunks', 'page_number')
    # ### end Alembic commands ###
