"""add stored_filename to manuals

Revision ID: a5613a1ee964
Revises: 091bf280f274
Create Date: 2026-09-02 09:02:43.160308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5613a1ee964'
down_revision: Union[str, Sequence[str], None] = '091bf280f274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuals', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuals', 'stored_filename')
    # ### end Alembic commands ###
