"""rename comparison and source columns, add rank

Revision ID: aecf9936b727
Revises: dd3b5c752d69
Create Date: 2026-09-07 12:48:22.474844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecf9936b727'
down_revision: Union[str, Sequence[str], None] = 'dd3b5c752d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_comparisons', sa.Column('model_b', sa.String(length=64), nullable=False))
    op.add_column('answer_comparisons', sa.Column('cost_b', sa.Numeric(precision=10, scale=6), nullable=False))
    op.drop_column('answer_comparisons', 'cost_a_b')
    op.drop_column('answer_comparisons', 'mode_b')
    op.add_column('message_sources', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('message_sources', sa.Column('rank', sa.Integer(), nullable=False))
    op.drop_column('message_sources', 'relevance_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_sources', sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('message_sources', 'rank')
    op.drop_column('message_sources', 'distance')
    op.add_column('answer_comparisons', sa.Column('mode_b', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('answer_comparisons', sa.Column('cost_a_b', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False))
    op.drop_column('answer_comparisons', 'cost_b')
    op.drop_column('answer_comparisons', 'model_b')
    # ### end Alembic commands ###
