"""message model and table answer_comparisons

Revision ID: dd3b5c752d69
Revises: c36c1bf22769
Create Date: 2026-09-06 12:26:03.652766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3b5c752d69'
down_revision: Union[str, Sequence[str], None] = 'c36c1bf22769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('best_distance', sa.Float(), nullable=False),
    sa.Column('model_a', sa.String(length=64), nullable=False),
    sa.Column('answer_a', sa.Text(), nullable=False),
    sa.Column('prompt_tokens_a', sa.Integer(), nullable=False),
    sa.Column('completion_tokens_a', sa.Integer(), nullable=False),
    sa.Column('cost_a', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms_a', sa.Integer(), nullable=False),
    sa.Column('mode_b', sa.String(length=64), nullable=False),
    sa.Column('answer_b', sa.Text(), nullable=False),
    sa.Column('prompt_tokens_b', sa.Integer(), nullable=False),
    sa.Column('completion_tokens_b', sa.Integer(), nullable=False),
    sa.Column('cost_a_b', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms_b', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('preferred', sa.String(length=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('model', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model')
    op.drop_table('answer_comparisons')
    # ### end Alembic commands ###
